Chapter 29
# 导入Scikit-Learn中鸢尾花数据
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习

In [97]:
import sklearn.datasets
import numpy as np
import pandas as pd

In [99]:
# 导入鸢尾花数据
iris = load_iris()
# 鸢尾花数据前4个特征，NumPy数组
X = iris.data

In [101]:
print(iris.feature_names)
# 鸢尾花数据标签：0、1、2

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [103]:
y = iris.target
print(np.unique(y))

[0 1 2]

In [105]:
# 鸢尾花文字标签
print(iris.target_names)

['setosa' 'versicolor' 'virginica']

In [107]:
# 创建数据帧
X_df = pd.DataFrame(X, 
                    columns = ['X1','X2','X3','X4'])
X_df.head()

    X1   X2   X3   X4
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [109]:
X_df.tail()

      X1   X2   X3   X4
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

In [111]:
round(X_df.describe(),2)

           X1      X2      X3      X4
count  150.00  150.00  150.00  150.00
mean     5.84    3.06    3.76    1.20
std      0.83    0.44    1.77    0.76
min      4.30    2.00    1.00    0.10
25%      5.10    2.80    1.60    0.30
50%      5.80    3.00    4.35    1.30
75%      6.40    3.30    5.10    1.80
max      7.90    4.40    6.90    2.50

In [113]:
housing = sklearn.datasets.fetch_california_housing()

In [115]:
X = housing.data

In [117]:
X

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [119]:
print(housing.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [121]:
y = housing.target
y #连续价格标签

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [123]:
len(y)

20640

In [125]:
X_df = pd.DataFrame(X)

In [127]:
X_df.head()

        0     1         2         3       4         5      6       7
0  8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1  8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2  7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3  5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4  3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25

In [129]:
X_df.tail()

            0     1         2         3       4         5      6       7
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

In [131]:
round(X_df.describe())

             0        1        2        3        4        5        6        7
count  20640.0  20640.0  20640.0  20640.0  20640.0  20640.0  20640.0  20640.0
mean       4.0     29.0      5.0      1.0   1425.0      3.0     36.0   -120.0
std        2.0     13.0      2.0      0.0   1132.0     10.0      2.0      2.0
min        0.0      1.0      1.0      0.0      3.0      1.0     33.0   -124.0
25%        3.0     18.0      4.0      1.0    787.0      2.0     34.0   -122.0
50%        4.0     29.0      5.0      1.0   1166.0      3.0     34.0   -118.0
75%        5.0     37.0      6.0      1.0   1725.0      3.0     38.0   -118.0
max       15.0     52.0    142.0     34.0  35682.0   1243.0     42.0   -114.0

In [143]:
diabetes = sklearn.datasets.load_diabetes()

In [157]:
X=diabetes.data #不能添加(),是提取数据
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [161]:
print(diabetes.feature_names)

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [169]:
y = diabetes.target #病人的疾病指标

In [171]:
print(np.unique(y)) #不重复的列出来

[ 25.  31.  37.  39.  40.  42.  43.  44.  45.  47.  48.  49.  50.  51.
  52.  53.  54.  55.  57.  58.  59.  60.  61.  63.  64.  65.  66.  67.
  68.  69.  70.  71.  72.  73.  74.  75.  77.  78.  79.  80.  81.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 107. 108. 109. 110. 111. 113. 114.
 115. 116. 118. 120. 121. 122. 123. 124. 125. 126. 127. 128. 129. 131.
 132. 134. 135. 136. 137. 138. 139. 140. 141. 142. 143. 144. 145. 146.
 147. 148. 150. 151. 152. 153. 154. 155. 156. 158. 160. 161. 162. 163.
 164. 166. 167. 168. 170. 171. 172. 173. 174. 175. 177. 178. 179. 180.
 181. 182. 183. 184. 185. 186. 187. 189. 190. 191. 192. 195. 196. 197.
 198. 199. 200. 201. 202. 206. 208. 209. 210. 212. 214. 215. 216. 217.
 219. 220. 221. 222. 225. 229. 230. 232. 233. 235. 236. 237. 241. 242.
 243. 244. 245. 246. 248. 249. 252. 253. 257. 258. 259. 261. 262. 263.
 264. 265. 268. 270. 272. 273. 274. 275. 276. 277. 279. 280. 281. 283.
 288. 292. 293. 295. 296. 297. 302. 303. 306. 308. 310. 311. 317. 321.
 332. 336. 341. 346.]

In [173]:
X_df.head()

        0     1         2         3       4         5      6       7
0  8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1  8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2  7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3  5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4  3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25

In [175]:
X_df.tail()

            0     1         2         3       4         5      6       7
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

In [185]:
round(X_df.describe(),1) #round为了保留几位小数,四舍五入

             0        1        2        3        4        5        6        7
count  20640.0  20640.0  20640.0  20640.0  20640.0  20640.0  20640.0  20640.0
mean       3.9     28.6      5.4      1.1   1425.5      3.1     35.6   -119.6
std        1.9     12.6      2.5      0.5   1132.5     10.4      2.1      2.0
min        0.5      1.0      0.8      0.3      3.0      0.7     32.5   -124.4
25%        2.6     18.0      4.4      1.0    787.0      2.4     33.9   -121.8
50%        3.5     29.0      5.2      1.0   1166.0      2.8     34.3   -118.5
75%        4.7     37.0      6.1      1.1   1725.0      3.3     37.7   -118.0
max       15.0     52.0    141.9     34.1  35682.0   1243.3     42.0   -114.3

In [201]:
digits = sklearn.datasets.load_digits() #这里需要括号

In [199]:
X = digits.data

In [203]:
print(digits.feature_names)

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']

In [205]:
y = digits.target
print(np.unique(y)) #数字0-9的标签

[0 1 2 3 4 5 6 7 8 9]

In [207]:
print(digits.target_names)

[0 1 2 3 4 5 6 7 8 9]

In [209]:
X_df = pd.DataFrame(X)

In [211]:
X_df.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0

In [213]:
X_df.tail()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [217]:
round(X_df.describe(),2)

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
count,1797.0,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,...,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00,1797.00
mean,0.0,0.30,5.20,11.84,11.85,5.78,1.36,0.13,0.01,1.99,...,3.73,0.21,0.00,0.28,5.56,12.09,11.81,6.76,2.07,0.36
std,0.0,0.91,4.75,4.25,4.29,5.67,3.33,1.04,0.09,3.20,...,4.92,0.98,0.02,0.93,5.10,4.37,4.93,5.90,4.09,1.86
min,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.0,0.00,1.00,10.00,10.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,1.00,11.00,10.00,0.00,0.00,0.00
50%,0.0,0.00,4.00,13.00,13.00,4.00,0.00,0.00,0.00,0.00,...,1.00,0.00,0.00,0.00,4.00,13.00,14.00,6.00,0.00,0.00
75%,0.0,0.00,9.00,15.00,15.00,11.00,0.00,0.00,0.00,3.00,...,7.00,0.00,0.00,0.00,10.00,16.00,16.00,12.00,2.00,0.00
max,0.0,8.00,16.00,16.00,16.00,16.00,16.00,15.00,2.00,16.00,...,16.00,13.00,1.00,9.00,16.00,16.00,16.00,16.00,16.00,16.00

In [221]:
linnerud = sklearn.datasets.load_linnerud()

In [239]:
X = linnerud.data

In [227]:
print(linnerud.feature_names) #列名

['Chins', 'Situps', 'Jumps']

In [237]:
y = linnerud.target
print(np.unique(y)) #体重腰围脉搏等,不一样的有很多
print(linnerud.target_names) #数据对应的指标名称 这里区别于鸢尾花书的种类,用三列表示一个人
#这里是回归问题,输出列名,鸢尾花是分类问题,输出列标签值.输出不一样

[ 31.  32.  33.  34.  35.  36.  37.  38.  46.  50.  52.  54.  56.  58.
  60.  62.  64.  68.  74. 138. 154. 156. 157. 162. 166. 167. 169. 176.
 182. 189. 191. 193. 202. 211. 247.]
['Weight', 'Waist', 'Pulse']

In [241]:
X_df = pd.DataFrame(X)

In [243]:
X_df.head()

      0      1      2
0   5.0  162.0   60.0
1   2.0  110.0   60.0
2  12.0  101.0  101.0
3  12.0  105.0   37.0
4  13.0  155.0   58.0

In [245]:
X_df.tail()

       0      1      2
15  12.0  210.0  120.0
16   4.0   60.0   25.0
17  11.0  230.0   80.0
18  15.0  225.0   73.0
19   2.0  110.0   43.0

In [247]:
round(X_df.describe(),2)

           0       1       2
count  20.00   20.00   20.00
mean    9.45  145.55   70.30
std     5.29   62.57   51.28
min     1.00   50.00   25.00
25%     4.75  101.00   39.50
50%    11.50  122.50   54.00
75%    13.25  210.00   85.25
max    17.00  251.00  250.00

In [249]:
wine = sklearn.datasets.load_wine()

In [253]:
X = wine.data
y = wine.target

In [259]:
print(wine.feature_names)
print(np.unique(y))
print(wine.target_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
[0 1 2]
['class_0' 'class_1' 'class_2']

In [261]:
X_df = pd.DataFrame(X)

In [263]:
X_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [265]:
X_df.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740.0
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750.0
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835.0
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840.0
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560.0

In [267]:
round(X_df.describe(),2)

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,178.00,178.00,178.00,178.00,178.00,178.00,178.00,178.00,178.00,178.00,178.00,178.00,178.00
mean,13.00,2.34,2.37,19.49,99.74,2.30,2.03,0.36,1.59,5.06,0.96,2.61,746.89
std,0.81,1.12,0.27,3.34,14.28,0.63,1.00,0.12,0.57,2.32,0.23,0.71,314.91
min,11.03,0.74,1.36,10.60,70.00,0.98,0.34,0.13,0.41,1.28,0.48,1.27,278.00
25%,12.36,1.60,2.21,17.20,88.00,1.74,1.20,0.27,1.25,3.22,0.78,1.94,500.50
50%,13.05,1.87,2.36,19.50,98.00,2.36,2.13,0.34,1.56,4.69,0.96,2.78,673.50
75%,13.68,3.08,2.56,21.50,107.00,2.80,2.88,0.44,1.95,6.20,1.12,3.17,985.00
max,14.83,5.80,3.23,30.00,162.00,3.88,5.08,0.66,3.58,13.00,1.71,4.00,1680.00

In [269]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [271]:
X = breast_cancer.data
y = breast_cancer.target

In [275]:
print(breast_cancer.feature_names)
print(np.unique(y))
print(breast_cancer.target_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
[0 1]
['malignant' 'benign']

In [277]:
X_df = pd.DataFrame(X)

In [279]:
X_df.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [281]:
X_df.tail()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [291]:
round(X_df.describe(),2) #round表示环绕,圆形等意思 四舍五入表示让数变得圆滑规整(靠近整数)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
count,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,...,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00
mean,14.13,19.29,91.97,654.89,0.10,0.10,0.09,0.05,0.18,0.06,...,16.27,25.68,107.26,880.58,0.13,0.25,0.27,0.11,0.29,0.08
std,3.52,4.30,24.30,351.91,0.01,0.05,0.08,0.04,0.03,0.01,...,4.83,6.15,33.60,569.36,0.02,0.16,0.21,0.07,0.06,0.02
min,6.98,9.71,43.79,143.50,0.05,0.02,0.00,0.00,0.11,0.05,...,7.93,12.02,50.41,185.20,0.07,0.03,0.00,0.00,0.16,0.06
25%,11.70,16.17,75.17,420.30,0.09,0.06,0.03,0.02,0.16,0.06,...,13.01,21.08,84.11,515.30,0.12,0.15,0.11,0.06,0.25,0.07
50%,13.37,18.84,86.24,551.10,0.10,0.09,0.06,0.03,0.18,0.06,...,14.97,25.41,97.66,686.50,0.13,0.21,0.23,0.10,0.28,0.08
75%,15.78,21.80,104.10,782.70,0.11,0.13,0.13,0.07,0.20,0.07,...,18.79,29.72,125.40,1084.00,0.15,0.34,0.38,0.16,0.32,0.09
max,28.11,39.28,188.50,2501.00,0.16,0.35,0.43,0.20,0.30,0.10,...,36.04,49.54,251.20,4254.00,0.22,1.06,1.25,0.29,0.66,0.21

In [295]:
olivetti_faces = sklearn.datasets.fetch_olivetti_faces() #不在本身的数据包用fetch抓取

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to /Users/arch/scikit_learn_data

In [297]:
X = olivetti_faces.data
y = olivetti_faces.target

In [305]:
print(np.unique(y))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]

In [307]:
X_df = pd.DataFrame(X)

In [309]:
X_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095
0,0.309917,0.367769,0.417355,0.442149,0.528926,0.607438,0.657025,0.677686,0.690083,0.685950,...,0.665289,0.669421,0.652893,0.661157,0.475207,0.132231,0.148760,0.152893,0.161157,0.157025
1,0.454545,0.471074,0.512397,0.557851,0.595041,0.640496,0.681818,0.702479,0.710744,0.702479,...,0.136364,0.157025,0.136364,0.148760,0.152893,0.152893,0.152893,0.152893,0.152893,0.152893
2,0.318182,0.400826,0.491736,0.528926,0.586777,0.657025,0.681818,0.685950,0.702479,0.698347,...,0.074380,0.132231,0.181818,0.136364,0.128099,0.148760,0.144628,0.140496,0.148760,0.152893
3,0.198347,0.194215,0.194215,0.194215,0.190083,0.190083,0.243802,0.404959,0.483471,0.516529,...,0.652893,0.636364,0.657025,0.685950,0.727273,0.743802,0.764463,0.752066,0.752066,0.739669
4,0.500000,0.545455,0.582645,0.623967,0.648760,0.690083,0.694215,0.714876,0.723140,0.731405,...,0.190083,0.161157,0.177686,0.173554,0.177686,0.177686,0.177686,0.177686,0.173554,0.173554

In [311]:
X_df.tail()

,0,1,2,3,4,5,6,7,8,9,...,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095
395,0.400826,0.495868,0.570248,0.632231,0.648760,0.640496,0.661157,0.636364,0.665289,0.698347,...,0.388430,0.396694,0.264463,0.099174,0.181818,0.243802,0.247934,0.161157,0.157025,0.136364
396,0.367769,0.367769,0.351240,0.301653,0.247934,0.247934,0.367769,0.512397,0.574380,0.628099,...,0.380165,0.334711,0.289256,0.285124,0.338843,0.404959,0.458678,0.487603,0.512397,0.549587
397,0.500000,0.533058,0.607438,0.628099,0.657025,0.632231,0.657025,0.669421,0.673554,0.702479,...,0.194215,0.148760,0.152893,0.161157,0.161157,0.173554,0.157025,0.177686,0.148760,0.190083
398,0.214876,0.219008,0.219008,0.223140,0.210744,0.202479,0.276859,0.400826,0.487603,0.549587,...,0.446281,0.392562,0.367769,0.409091,0.479339,0.524793,0.545455,0.574380,0.590909,0.603306
399,0.516529,0.462810,0.280992,0.252066,0.247934,0.367769,0.574380,0.615702,0.661157,0.615702,...,0.276859,0.264463,0.293388,0.301653,0.293388,0.322314,0.322314,0.359504,0.355372,0.384298

In [313]:
round(X_df.describe(),2)

,0,1,2,3,4,5,6,7,8,9,...,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095
count,400.00,400.00,400.00,400.00,400.00,400.00,400.00,400.00,400.00,400.00,...,400.00,400.00,400.00,400.00,400.00,400.00,400.00,400.00,400.00,400.00
mean,0.40,0.43,0.48,0.52,0.55,0.59,0.62,0.65,0.66,0.68,...,0.36,0.37,0.36,0.36,0.34,0.34,0.34,0.32,0.31,0.31
std,0.18,0.19,0.19,0.19,0.19,0.18,0.17,0.16,0.15,0.14,...,0.16,0.18,0.18,0.19,0.19,0.19,0.20,0.19,0.18,0.18
min,0.09,0.07,0.09,0.04,0.11,0.11,0.12,0.12,0.12,0.14,...,0.05,0.04,0.05,0.05,0.03,0.01,0.05,0.06,0.06,0.03
25%,0.24,0.27,0.31,0.38,0.45,0.52,0.54,0.58,0.60,0.61,...,0.23,0.21,0.22,0.20,0.18,0.18,0.17,0.17,0.17,0.17
50%,0.39,0.46,0.51,0.55,0.58,0.62,0.65,0.67,0.68,0.70,...,0.37,0.37,0.34,0.33,0.32,0.31,0.30,0.29,0.27,0.27
75%,0.53,0.58,0.64,0.67,0.70,0.71,0.74,0.76,0.77,0.78,...,0.48,0.50,0.50,0.50,0.48,0.46,0.46,0.45,0.41,0.42
max,0.81,0.82,0.87,0.89,0.87,0.87,0.87,0.87,0.87,0.87,...,0.79,0.90,0.89,0.90,0.83,0.86,0.92,0.93,0.88,0.82

In [315]:
lfw_people = sklearn.datasets.fetch_lfw_people()

In [316]:
X = lfw_people.data
y = lfw_people.target

In [319]:
print(np.unique(y))

[   0    1    2 ... 5746 5747 5748]

In [321]:
print(lfw_people.target_names)

['AJ Cook' 'AJ Lamas' 'Aaron Eckhart' ... 'Zumrati Juma' 'Zurab Tsereteli'
 'Zydrunas Ilgauskas']

In [323]:
X_df = pd.DataFrame(X)

In [325]:
X_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2904,2905,2906,2907,2908,2909,2910,2911,2912,2913
0,0.171242,0.150327,0.122876,0.121569,0.137255,0.147712,0.177778,0.291503,0.401307,0.479739,...,0.133333,0.103268,0.082353,0.071895,0.056209,0.065359,0.087582,0.096732,0.100654,0.094118
1,0.619608,0.628758,0.670588,0.661438,0.636601,0.635294,0.620915,0.641830,0.645752,0.627451,...,0.884967,0.781699,0.669281,0.473203,0.405229,0.457516,0.525490,0.546405,0.534641,0.507190
2,0.313726,0.325490,0.345098,0.420915,0.533333,0.593464,0.603922,0.640523,0.653595,0.667974,...,0.690196,0.734641,0.862745,0.879739,0.841830,0.811765,0.780392,0.755556,0.577778,0.244444
3,0.044444,0.043137,0.044444,0.049673,0.053595,0.058824,0.058824,0.049673,0.049673,0.054902,...,0.470588,0.474510,0.478431,0.464052,0.453595,0.467974,0.478431,0.458824,0.409150,0.354248
4,0.108497,0.104575,0.104575,0.112418,0.112418,0.108497,0.120261,0.147712,0.143791,0.121569,...,0.056209,0.032680,0.028758,0.041830,0.061438,0.061438,0.056209,0.054902,0.064052,0.077124

In [327]:
X_df.tail()

,0,1,2,3,4,5,6,7,8,9,...,2904,2905,2906,2907,2908,2909,2910,2911,2912,2913
13228,0.115033,0.098039,0.095425,0.117647,0.190850,0.278431,0.354248,0.411765,0.456209,0.488889,...,0.637909,0.343791,0.103268,0.066667,0.091503,0.058824,0.050980,0.064052,0.067974,0.120261
13229,0.416993,0.433987,0.501961,0.580392,0.639216,0.686275,0.715033,0.725490,0.730719,0.738562,...,0.411765,0.427451,0.443137,0.426144,0.376471,0.257516,0.279739,0.366013,0.277124,0.175163
13230,0.145098,0.155556,0.210458,0.290196,0.418301,0.483660,0.478431,0.482353,0.490196,0.499346,...,0.521569,0.631373,0.216993,0.220915,0.269281,0.256209,0.245752,0.262745,0.253595,0.211765
13231,0.069281,0.091503,0.236601,0.471895,0.530719,0.535948,0.522876,0.482353,0.440523,0.427451,...,0.801307,0.951634,0.971242,0.939869,0.924183,0.954248,0.958170,0.874510,0.566013,0.252288
13232,0.231373,0.200000,0.062745,0.074510,0.173856,0.265359,0.381699,0.462745,0.516340,0.541176,...,0.220915,0.236601,0.291503,0.360784,0.410458,0.436601,0.466667,0.457516,0.401307,0.588235

In [329]:
round(X_df.describe(),2)

,0,1,2,3,4,5,6,7,8,9,...,2904,2905,2906,2907,2908,2909,2910,2911,2912,2913
count,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,...,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00,13233.00
mean,0.28,0.29,0.31,0.34,0.37,0.40,0.43,0.46,0.48,0.50,...,0.38,0.40,0.41,0.42,0.43,0.42,0.42,0.41,0.39,0.38
std,0.20,0.20,0.20,0.20,0.20,0.21,0.21,0.20,0.20,0.20,...,0.21,0.23,0.24,0.25,0.26,0.26,0.27,0.27,0.27,0.27
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.13,0.14,0.15,0.18,0.21,0.24,0.27,0.31,0.35,0.38,...,0.23,0.23,0.23,0.22,0.22,0.20,0.19,0.17,0.16,0.14
50%,0.24,0.26,0.28,0.32,0.36,0.40,0.44,0.47,0.49,0.52,...,0.36,0.38,0.39,0.40,0.40,0.40,0.39,0.37,0.35,0.33
75%,0.40,0.42,0.45,0.48,0.51,0.55,0.58,0.60,0.62,0.64,...,0.51,0.54,0.56,0.59,0.60,0.61,0.61,0.60,0.58,0.57
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00