In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris

In [71]:
data = load_iris()
X_df_iris = pd.DataFrame(data.data,columns = data.feature_names)

In [73]:
target = data.target
target_names = []
for i in np.arange(len(target)):
    target_name_idx = target[i]
    target_name = data.target_names[target_name_idx]
    target_names.append(target_name)

X_df_iris['species'] = target_names

In [75]:
X_df = X_df_iris.iloc[:,:4]

X_df.columns = ['Sepal length (cm)',
                'Sepal width (cm)',
                'Petal lenght (cm)',
                'Petal widht (cm)']

In [77]:
X_df.head()

   Sepal length (cm)  Sepal width (cm)  Petal lenght (cm)  Petal widht (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [79]:
Sigma = X_df.cov() #协方差矩阵
Sigma.columns = Sigma.columns.str.replace('(cm)','',regex = False)
Sigma.index = Sigma.index.str.replace('(cm)','',regex = False)
Sigma

               Sepal length   Sepal width   Petal lenght   Petal widht
Sepal length        0.685694     -0.042434       1.274315      0.516271
Sepal width        -0.042434      0.189979      -0.329656     -0.121639
Petal lenght        1.274315     -0.329656       3.116278      1.295609
Petal widht         0.516271     -0.121639       1.295609      0.581006

In [81]:
P = X_df.corr() #线性相关系数矩阵
P.columns = P.columns.str.replace(' (cm)','',regex = False)
P.index = P.index.str.replace(' (cm)','',regex = False)
P

              Sepal length  Sepal width  Petal lenght  Petal widht
Sepal length      1.000000    -0.117570      0.871754     0.817941
Sepal width      -0.117570     1.000000     -0.428440    -0.366126
Petal lenght      0.871754    -0.428440      1.000000     0.962865
Petal widht       0.817941    -0.366126      0.962865     1.000000

In [83]:
#Q1

In [85]:
Lambdas_sigma,V_sigma = np.linalg.eig(Sigma)

In [87]:
Lambdas_sigma

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [89]:
V_sigma

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])

In [91]:
#Q2

In [93]:
Lambdas_P,V_P = np.linalg.eig(P)

In [95]:
Lambdas_P

array([2.91849782, 0.91403047, 0.14675688, 0.02071484])

In [97]:
V_P

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])